# Generated by Django 4.1.7 on 2023-03-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_tasks_is_deleted_project_is_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
