# Generated by Django 4.1.7 on 2023-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_userproject_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор'),
        ),
    ]
