# Generated by Django 4.1.7 on 2023-03-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_delete_userproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
